codecov:
  notify:
    require_ci_to_pass: false
comment: false
coverage:
  range: "75...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: "0.5%"
    patch: false
    changes: false
